[book]
authors = ["Hermilo Cortés"]
language = "en"
multilingual = false
src = "src"
title = "InvESt-Tec Monterrey"

[output.html]
default-theme = "light"
mathjax-support = true

[output.html.playground]
editable = true