[book]
authors = ["Hermilo Cortés"]
language = "en"
multilingual = false
src = "src"
title = "Análisis de decisiones bajo condiciones de incertidumbre"

[output.html]
default-theme = "light"
mathjax-support = true

[output.html.playground]
editable = true